"""Ajout status, start_time, end_time à Video et status à Court

Revision ID: 4b4dcdcd2ce8
Revises: 
Create Date: 2025-07-28 15:36:42.116014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4dcdcd2ce8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Supprimer la ligne problématique - la table club_history n'existe pas
    # op.drop_table('club_history')
    
    with op.batch_alter_table('club_action_history', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('AVAILABLE', 'RECORDING', 'MAINTENANCE', name='courtstatus'), nullable=False))
        batch_op.alter_column('qr_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('player_club_follows', schema=None) as batch_op:
        batch_op.drop_column('followed_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('facebook_id')
        batch_op.drop_column('google_id')
        batch_op.drop_column('profile_photo_url')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('RECORDING', 'COMPLETED', 'FAILED', name='videostatus'), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('duration')
        batch_op.drop_column('credits_cost')
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('credits_cost', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('profile_photo_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('facebook_id', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('player_club_follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('court', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('qr_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('status')

    with op.batch_alter_table('club_action_history', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('club_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=13), nullable=False),
    sa.Column('action_details', sa.TEXT(), nullable=True),
    sa.Column('performed_by_id', sa.INTEGER(), nullable=False),
    sa.Column('performed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
